### ISSUE TITLE
problem_reading_documents

### ISSUE THREAD

**Issue by ghost** [clips/bratreader#2] opened 2017-07-03 13:57 UTC
If i point RepoModel to the exact directory containing my .txt and .ann files, i get:

```
>>> r=RepoModel("/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog/data/tesi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bratreader/repomodel.py", line 48, in __init__
    annotations, context = importpath("/".join([pathtorepo, path]))
  File "bratreader/ann_filehandler.py", line 18, in importann
    annotations = readannfile(pathtofile)
  File "bratreader/ann_filehandler.py", line 209, in readannfile
    return _evaluate_annotations(anndict)
  File "bratreader/ann_filehandler.py", line 117, in _evaluate_annotations
    annotationobjects = _createannotationobjects(annotations["T"])
  File "bratreader/ann_filehandler.py", line 60, in _createannotationobjects
    t, repr = t.split("\t")
ValueError: too many values to unpack
>>> 
```
Instead pointing to brat folder seems to work, but the empty braces may suggest no document is found:

```
>>> r=RepoModel("/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog")
>>> r.documents
{}
```
Moreover, what am I supposed to replace the key 001 in `doc = r.documents[001]` with? File name? Or the key is automatically assign?

**Comment by stephantul** [comment] 2017-07-03 14:08
Hey,

The first way you are doing it is correct, but I can't really see what is causing the error without looking at the .ann files themselves. It might be the result of something in your files we didn't encounter in the set of documents we used to create this. I'll take a look at it.

The key is assigned automatically on the basis of the filename, so if you `.ann` file is named `001.ann`, that document will get the key `001`.

**Comment by stephantul** [comment] 2017-07-03 14:19
Hey, 

I just checked and everything is working the way it is supposed to here, so the problem probably lies in the fact that your files contain some type of specification which is not in our files. If you want you can send me some snippets, maybe that way we can solve the problem.

**Comment by ghost** [comment] 2017-07-03 14:46
Ok. Thanks, Stephan. The directory named "tesi" contains only one `.txt` file (just few sentences) and its relative `.ann` file, in addition to configuration files.

`.ann` file:

```
> T1	Argument_Structure 0 9	Prendiamo
> E1	Argument_Structure:T1 Theme:T2
> T2	Information_Object 10 41	l' esempio dell' Unione europea
> A1	Constituent_Type T2 SN
> A2	Syntactic_Function T2 O
> T3	Argument_Structure 65 79	si	prenderanno
> E2	Argument_Structure:T3 Theme:T5 Manner:T4
> T4	Mode 80 93	a maggioranza
> A3	Constituent_Type T4 SPrep
> A4	Syntactic_Function T4 C
> T5	Information_Object 52 64	le decisioni
> A5	Constituent_Type T5 SN
> A6	Syntactic_Function T5 S
> T6	Argument_Structure 103 124	vengono a prendersela
> E3	Argument_Structure:T6 Patient:T7
> T7	Social_Group 125 132	con noi
> A7	Constituent_Type T7 SPrep
> A8	Syntactic_Function T7 C
```
`annotation.conf`:

```
[entities]

# ontological categories

Entity
	Abstract_Entity
		Social_Entity
			Information_Object
			Institution
		Property
			Quality
				Temporal_Quality
				Spatial_Quality
				Mode
			Function
		Region
			Temporal_Region
			Spatial_Region				
	Concrete_Entity
		Object
			Artifact
			Natural_Object
			Place
			Substance
			Non_Material_Object
			Agent
				Social_Group
				Person
				Animal
		Event
			Process
				Natural_Process
				Mental_Process
				Action
			State
				Physical_State
				Body_State
				Psychological_State
		Period
	Collection
		
[relations]

[events]

# semantic roles

Argument_Structure	Distance:<ENTITY>, Location:<ENTITY>, Initial_Location:<ENTITY>, End_Location:<ENTITY>, Path:<ENTITY>, Duration:<ENTITY>, Frequency:<ENTITY>, Initial_Time:<ENTITY>, End_Time:<ENTITY>, Amount:<ENTITY>, Manner:<ENTITY>, Purpose:<ENTITY>, Agent:<ENTITY>, Cause:<ENTITY>, Result:<ENTITY>, Patient:<ENTITY>, Experiencer:<ENTITY>, Instrument:<ENTITY>, Theme:<ENTITY>, Source:<ENTITY>, Goal:<ENTITY>, Beneficiary:<ENTITY>, Attribute:<ENTITY>  

[attributes]

Syntactic_Function	Arg:<ENTITY>,	Value:S|S*|S0|O|C|O*|C*

Constituent_Type	Arg:<ENTITY>, Value:SN|SPron|SPrep|SAvv|SAgg|SFr

Class_of_Verbs		Arg:<EVENT>, Value:Transitive_Verb|Inaccusative_Verb|Inergative_Verb|Pronominal_Verb 
```

`visual.conf `:

```
[labels]

Information_Object | Information_Object | In_Ob
Temporal_Quality | Temporal_Quality | Te_Qu
Spatial_Quality | Spatial_Quality | Sp_Qu
Temporal_Region | Temporal_Region | Te_Re
Spatial_Region | Spatial_Region	| Sp_Re
Natural_Object | Natural_Object | Na_Ob
Non_Material_Object | Non_Material_Object | No_Ma_Ob
Social_Group | Social_Group | S_G
Natural_Process | Natural_Process | Na_Pr
Mental_Process | Mental_Process | Me_Pr
Physical_State | Physical_State | Ph_St	
Body_State | Body_State | Bo_St
Psychological_State | Psychological_State | Ps_St

Initial_Location | Initial_Location | In_Lo
End_Location | End_Location | En_Lo
Initial_Time | Initial_Time | In-Ti
End_Time | End_Time | En_Ti

Transitive_Verbs | Transitive_Verbs | TRANS
Inaccusative_Verbs | Inaccusative_Verbs | INACC
Inergative_Verbs | Inergative_Verbs | INERG
Pronominal_Verbs | Pronominal_Verbs | PRON

Argument_Structure | Argument_Structure | ARG_STR

[drawing]
```
`tool.conf` contains no specification.
It seems all correct to me.

Any idea?

**Comment by stephantul** [comment] 2017-07-03 14:58
I was able to reproduce and fix the error, thanks for notifying us of this problem. The problem (which did not occur in our dataset) is that one of the Targets you specified had a tab character inside of it. Because the BRAT format uses tabs as delimiters, the code broke
I also fixed the documentation and changed the directory structure a little bit.

Please let me know if this fixes your issues.

**Comment by ghost** [comment] 2017-07-03 15:20
Ok, now `repomodel` seems to find the right folder, but then it fails to get the specific document (i.e. the pair `prendere.txt`/`prendere.ann` in my case):

```
>>> r=RepoModel("/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog/data/tesi")
(6, 7)
>>> r.documents
{'/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog/data/tesi/prendere': <bratreader.annotateddocument.AnnotatedDocument object at 0x7fb3a59d7d90>}
>>> doc = r.documents[prendere]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'prendere' is not defined
>>> doc = r.documents['prendere']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'prendere'
>>> doc = r.documents["prendere"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'prendere'
```

**Comment by stephantul** [comment] 2017-07-03 15:35
You can view all keys by printing `r.documents` (`print(r.documents)`). Could you post the output of this please?

EDIT: this bug should already be fixed. Could you clone again?

**Comment by ghost** [comment] 2017-07-03 15:49
Already cloned, but nothing changes:

```
>>> r.documents
{'/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog/data/tesi/prendere': <bratreader.annotateddocument.AnnotatedDocument object at 0x7ffbf0316d90>}
>>> print(r.documents)
{'/home/giuliano/Documenti/brat-v1.3_Crunchy_Frog/data/tesi/prendere': <bratreader.annotateddocument.AnnotatedDocument object at 0x7ffbf0316d90>}
>>> doc = r.documents["prendere"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'prendere'
```

**Comment by stephantul** [comment] 2017-07-03 17:14
Yep, I forgot to push the fix. It's done now.

**Comment by ghost** [comment] 2017-07-03 19:37
Ok. There's some problem with Unicode characters, but it must be due to Python.

```
>>> r.documents
{'prendere': <bratreader.annotateddocument.AnnotatedDocument object at 0x7fec4d6efdd0>}
>>> doc = r.documents["prendere"]
>>> print(doc.sentences) 
[Prendiamo l' esempio dell' Unione europea., , solo se le decisioni si prenderanno a maggioranza., , Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 43: ordinal not in range(128)
>>> print(doc.annotations) 
[Annotation: r g u m e n t _ S t r u c t u r e   0   9, Annotation: n f o r m a t i o n _ O b j e c t   1 0   4 1, Annotation: n f o r m a t i o n _ O b j e c t   1 0   4 1, Annotation: n f o r m a t i o n _ O b j e c t   1 0   4 1, Annotation: n f o r m a t i o n _ O b j e c t   1 0   4 1, Annotation: n f o r m a t i o n _ O b j e c t   1 0   4 1, Annotation: n f o r m a t i o n _ O b j e c t   5 2   6 4, Annotation: n f o r m a t i o n _ O b j e c t   5 2   6 4, Annotation: r g u m e n t _ S t r u c t u r e   6 5   7 9, Annotation: n f o r m a t i o n _ O b j e c t   5 2   6 4, Annotation: r g u m e n t _ S t r u c t u r e   6 5   7 9, Annotation: r g u m e n t _ S t r u c t u r e   6 5   7 9, Annotation: o d e   8 0   9 3, Annotation: o d e   8 0   9 3, Annotation: o d e   8 0   9 3, Annotation: r g u m e n t _ S t r u c t u r e   1 0 3   1 2 4, Annotation: r g u m e n t _ S t r u c t u r e   1 0 3   1 2 4, Annotation: r g u m e n t _ S t r u c t u r e   1 0 3   1 2 4, Annotation: o c i a l _ G r o u p   1 2 5   1 3 2, Annotation: r g u m e n t _ S t r u c t u r e   1 0 3   1 2 4, Annotation: o c i a l _ G r o u p   1 2 5   1 3 2]
```
Anyway, you deleted erroneously the last line (`r.export_xml_corpus("corpus.xml"))` from README, that also doesn't seem to work:

```
>>> r.export_xml_corpus("mycorpus.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RepoModel' object has no attribute 'export_xml_corpus'
>>> r.export_xml_corpus("prendere.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RepoModel' object has no attribute 'export_xml_corpus'
>>> r.export_xml_prendere("prendere.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RepoModel' object has no attribute 'export_xml_prendere'
```

**Comment by stephantul** [comment] 2017-07-03 19:52
The method has been renamed to `save_xml(path)`, where path is the path to a folder. This folder will get 1 XML document per original document. 

XML loading is currently not supported, and will be added soon.

**Comment by ghost** [comment] 2017-07-03 20:13
I'm so sorry to bother you again, but something seems to lack:

```
>>> r.save_xml("/home/giuliano/Documenti")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bratreader/repomodel.py", line 61, in save_xml
    document.export_xml(path)
AttributeError: 'AnnotatedDocument' object has no attribute 'export_xml'
```

**Comment by stephantul** [comment] 2017-07-03 20:14
Sorry, should be fixed now. Again forgot to push my commits.

**Comment by ghost** [comment] 2017-07-03 20:43
It seems to work correctly now.
Thank you for your time, Stephan.

**Closed as completed** 2017-07-03 20:43 UTC
